[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "gonzago-design-tools"
version = "0.0.1"
dependencies = [
  "typer",
  "pydantic",
  "pydantic-extra-types",
  "pydantic-settings",
  "semver",
  "pycountry",
  "pyyaml",
  "jinja2",
  "pillow",
  "scour",
]
requires-python = "^3.10"
authors = [
  {name = "David Krummenacher"},
  {name = "Gonzago Framework contributors"}
]
description = "Automation and tooling for Gonzago Framework design elements."
readme = "README.md"
license = "MIT"
keywords = ["Gonzago", "Godot", "tools", "assets"]

[project.urls]
repository = "https://github.com/godot-gonzago/gonzago-design"
Issues = "https://github.com/godot-gonzago/gonzago-design/issues"

[project.scripts]
gonzago = 'gonzago.cli.main:app'

[tool.poetry]
packages = [
  { include = "gonzago" }
]

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
